#ifndef SPRITE_DEFINITIONS_H
#define SPRITE_DEFINITIONS_H

#include <genesis.h>

// ANIMATIONS
#define ANIM_WALK 0
#define ANIM_IDLE 1

#define TILE_NO_FLIP TILE_ATTR(PAL2, TRUE, FALSE, FALSE)
#define TILE_FLIP_V  TILE_ATTR(PAL2, TRUE,  TRUE, FALSE)
#define TILE_FLIP_H  TILE_ATTR(PAL2, TRUE, FALSE,  TRUE)
#define TILE_FLIP_VH TILE_ATTR(PAL2, TRUE,  TRUE,  TRUE)

#endif /* SPRITE_DEFINITIONS_H */
